### ISSUE TITLE
请教一个报错问题

### ISSUE THREAD

**Issue by Vivianluolita** [Jinyang79/vue-ts-memo#24]
你好。我想问一个问题，因为我把vuex state 也是用同样的方法，用构造器实例化，在我自己的项目里。但是调用class构造器的edit方法报错了。虽然不影响功能，也可以执行。[vuex] do not mutate vuex store state outside mutation handlers.这个错是不是因为我的本地项目是vue2 不是vue3 和 ts 的原因？但我感觉我写的构造器以及edit方法 在vue里面调用和你的例子是一样的。

**Comment by Vivianluolita** [comment]
因为我感觉vuex改变state值一般是通过action或者mutation，但是class 定义一个state ,调构造器就改变state值。（比如edit方法）是不是不太符合vuex的使用，但是你的项目却没报错，我有点疑惑。

**Comment by Jinyang79** [comment]
> 因为我感觉vuex改变state值一般是通过action或者mutation，但是class 定义一个state ,调构造器就改变state值。（比如edit方法）是不是不太符合vuex的使用，但是你的项目却没报错，我有点疑惑。

@Vivianluolita 这个项目 edit 方法是直接改变 localstorage 的值，然后渲染的 memoList 直接在 store 中，通过this.dataHelper.readData() 读取 localstorage 的值，包括新增和删除都是这样，只有 showEditMemo 展示编辑备忘录操作是通过 mutation 的方式改变

当然，编辑操作使用 mutation 是完全可以的，这里只是一种实现方式，与常规改变 state 方式不太一样。

**Comment by Vivianluolita** [comment]
let store = new Vuex.Store({
  strict:true
}

我知道为什么了，因为我的项目是严格模式。如果你也加上这个严格模式，就会报和我一样的错。
